### PR TITLE
Update to 1.19.4

### PR DESCRIPTION
**Pull request by TheMeinerLP**
## Proposed changes

Add some mass of code for make minestom 1.19.4 ready!
From: https://github.com/Minestom/Minestom/pull/1873

> prev pr https://github.com/Minestom/Minestom/pull/1858
> issue https://github.com/Minestom/Minestom/issues/1787

Thanks to @MelonHell

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [X] I have read the CONTRIBUTING.md
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you
did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by MelonHell** [comment]
😎

**Comment by TheMeinerLP** [comment]
Hey @MelonHell can you maybe confirm the code is correct.

**Comment by MelonHell** [comment]
> Hey @MelonHell can you maybe confirm the code is correct. 

I'm not even sure if my code is correct :)

**Comment by MelonHell** [comment]
> Hey @MelonHell can you maybe confirm the code is correct. 

I'm not even sure if my code is correct :)

**Comment by MelonHell** [comment]
My PR needs more testing, as well as reviews by people who are better at it.

**Comment by TheMeinerLP** [comment]
> 

Okay good to know. We do that and you get feedback when you happy with it 😄

**Comment by theEvilReaper** [comment]
Do we have tests for the new code parts?

**Comment by TheMeinerLP** [comment]
> Do we have tests for the new code parts?

Some but not all

**Review by theEvilReaper — APPROVED** [review]
LGTM

**Comment by TheMeinerLP** [comment]
Fixes https://github.com/Minestom/Minestom/issues/1787

**Pull request merged**
